### ISSUE TITLE
Обработка исключений

### ISSUE THREAD

**Issue by ACM-Unit** [JavaStudentAlex/SecondLab#9]
} catch (XMLStreamException e) {
            throw new IOException();
	либо
    } catch (Exception e) {
            throw new StartTimeInvalidException();
    } 	
	 либо
	catch (CloneNotSupportedException e){
            throw new RuntimeException("Error in cloning Task");
    }
и т.д.	 
Вот так делать не нужно. Это приведет к потере оригинального исключения, и к невозможности найти причину в случае падения. Нужно исправить

**Comment by JavaStudentAlex** [comment]
Fixed by 6500cfdbf27e60de831c1e59530b68fb4db05cba. The first example fixed, The third - class was removed as not needy class. The second is the neseccary because of the all exception in the try block are about parsing some values.
